spring:
  application:
    name: release-notes

  # Database Configs
  datasource:
    url: jdbc:postgresql://localhost:5432/release_notes
    username: postgres
    password: novaSenha

  # JPA/Hibernate Configs
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Liquibase Configs
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # AI Configs (Hugging Face)
ai:
  huggingface:
    api-key:
    base-url: https://router.huggingface.co
    model: meta-llama/Llama-3.1-8B-Instruct
    temperature: 0.3