spring:
  application:
    name: notes-generator

  # Database Configs
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_generator
    username: postgres
    password: ""

  # JPA/Hibernate Configs
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Liquibase Configs
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # AI Configs (Hugging Face)
  ai:
    openai:
      api-key: ${HF_API_KEY}
      base-url: https://api-inference.huggingface.co/v1/
      chat:
        options:
          model: meta-llama/Meta-Llama-3-8B-Instruct
          temperature: 0.3